//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiXamarin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleVenta
    {
        public int IIDVENTA { get; set; }
        public int IIDASIENTO { get; set; }
        public Nullable<int> IIDVIAJE { get; set; }
        public Nullable<int> IIDBUS { get; set; }
        public Nullable<decimal> PRECIO { get; set; }
    
        public virtual Asiento Asiento { get; set; }
        public virtual Bus Bus { get; set; }
        public virtual Venta Venta { get; set; }
        public virtual Viaje Viaje { get; set; }
    }
}
