//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiXamarin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Empleado()
        {
            this.Venta = new HashSet<Venta>();
        }
    
        public int IIDEMPLEADO { get; set; }
        public string NOMBRE { get; set; }
        public string APPATERNO { get; set; }
        public string APMATERNO { get; set; }
        public Nullable<System.DateTime> FECHACONTRATO { get; set; }
        public Nullable<decimal> SUELDO { get; set; }
        public Nullable<int> IIDTIPOUSUARIO { get; set; }
        public Nullable<int> IIDTIPOCONTRATO { get; set; }
        public Nullable<int> IIDSEXO { get; set; }
        public Nullable<int> BHABILITADO { get; set; }
    
        public virtual Sexo Sexo { get; set; }
        public virtual TipoUsuario TipoUsuario { get; set; }
        public virtual TipoContrato TipoContrato { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Venta> Venta { get; set; }
    }
}
